apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: generic-claim
        - name: config
          configMap:
            name: exercises-config
            items:
              - key: "information.txt"
                path: "information.txt"
      containers:
        - name: log-output-server
          image: EXERCISES/LOGOUTPUT
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: exercises-config
                  key: message
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-volume
            - mountPath: /config
              name: config
              readOnly: true
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: http
              path: /healthz
        - name: log-output-writer
          image: EXERCISES/LOGOUTPUT
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-volume
          command: ["python3", "writer.py"]
