apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-todo-job
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: create-todo
              image: todo-backend:4.0
              imagePullPolicy: IfNotPresent
              command: ["python3", "create_todo.py"]
              envFrom:
                - configMapRef:
                    name: project-config
          restartPolicy: Never
