apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: server_port
                  name: project-config
            - name: MAX_TODO_LENGTH
              valueFrom:
                configMapKeyRef:
                  key: max_todo_length
                  name: project-config
