apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-rate
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: config
          configMap:
            name: exercises-config
            items:
              - key: ping_pong_db.config
                path: ping_pong_db.config
      containers:
        - name: ping-pong
          image: EXERCISES/PINGPONG
          volumeMounts:
            - mountPath: /config
              name: config
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              port: http
              path: /healthz
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: http
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: exercises
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 30s
    interval: 30s
    count: 10
    failureLimit: 0
    successCondition: result < 1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[5m]))
