apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - manifests/configmap.yaml
  - manifests/persistentvolumeclaim-gke.yaml
  - manifests/gateway.yaml
  - manifests/httproute.yaml
  - todo_app/manifests/deployment.yaml
  - todo_app/manifests/service.yaml
  - todo_backend/manifests/deployment.yaml
  - todo_backend/manifests/service.yaml
  - todo_backend/manifests/statefulset.yaml
  - todo_backend/manifests/cronjob.yaml
  - broadcaster/manifests/deployment.yaml
images:
  - name: PROJECT/APP
    newName: drellxor/todo-app
    newTag: "6.0"
  - name: PROJECT/BACKEND
    newName: drellxor/todo-backend
    newTag: "7.0"
  - name: PROJECT/BROADCASTER
    newName: drellxor/todo-broadcaster
