apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- manifests/configmap.yaml
- manifests/persistentvolumeclaim-gke.yaml
- manifests/gateway.yaml
- manifests/httproute.yaml
- todo_app/manifests/deployment.yaml
- todo_app/manifests/service.yaml
- todo_backend/manifests/deployment.yaml
- todo_backend/manifests/service.yaml
- todo_backend/manifests/statefulset.yaml
- todo_backend/manifests/cronjob.yaml
- broadcaster/manifests/deployment.yaml
images:
- name: PROJECT/APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-app
  newTag: main-c58d57d120bbe574071754b088a3661019c483ab
- name: PROJECT/BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-backend
  newTag: main-c58d57d120bbe574071754b088a3661019c483ab
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/todo-broadcaster
  newTag: main-c58d57d120bbe574071754b088a3661019c483ab
