apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/persistentvolumeclaim-gke.yaml
- manifests/gateway.yaml
- manifests/httproute.yaml
- log_output/manifests/deployment.yaml
- log_output/manifests/service.yaml
- ping_pong/manifests/rollout.yaml
- ping_pong/manifests/service.yaml
- ping_pong/manifests/statefulset.yaml
images:
- name: EXERCISES/LOGOUTPUT
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/log-output
  newTag: main-e273931a504c52060531898534f775967e9add99
- name: EXERCISES/PINGPONG
  newName: europe-north1-docker.pkg.dev/dwk-gke-508413/dwk-repo/ping-pong
  newTag: main-e273931a504c52060531898534f775967e9add99
