apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: log-output-claim
      containers:
        - name: log-output-server
          image: log-output:4.0
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-log-output
        - name: log-output-writer
          image: log-output:4.0
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-log-output
          command: ["python3", "writer.py"]
