apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: todo-app
          image: todo-app:6.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: server_port
                  name: project-config
            - name: IMAGE_FILE
              valueFrom:
                configMapKeyRef:
                  key: image_file
                  name: project-config
            - name: IMAGE_MAX_AGE_SECONDS
              valueFrom:
                configMapKeyRef:
                  key: image_max_age_seconds
                  name: project-config
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  key: image_url
                  name: project-config
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  key: todo_backend_url
                  name: project-config
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: shared-volume
